### ISSUE TITLE
KaSim3 issue

### ISSUE THREAD

**Issue by glucksfall** [pysb/pysb#300] opened 2017-10-06 14:57 UTC
Hello everyone,

I tried to solve a model using KaSim3 (KaSim 3.5-250915) and PySB raised the following error:

Traceback (most recent call last):
  File "Untitled.py", line 47, in <module>
    kappa_ssa_sim = kappa.run_simulation(model, time = t_end, points = 1000)
  File "/usr/local/lib/python3.5/dist-packages/pysb/kappa.py", line 179, in run_simulation
    raise KasimInterfaceError(p_out + '\n' + p_err)
TypeError: can't concat bytes to str

Best regards to all
Rodrigo

**Comment by alubbock** [comment] 2017-10-19 19:48
Hi Rodrigo,

Thanks for bringing this to our attention. Kappa is throwing an error for your model, but it is being masked by the PySB error above. I've created pull request which fixes that PySB error (#306). In the meantime, you could try running your model under Python 2, which should show the underlying Kappa error. We'll get this fix merged ASAP.

Sorry for the inconvenience.

Thanks,
Alex

**Comment by alubbock** [comment] 2018-01-13 02:52
Hi Rodrigo,

This issue should now be fixed, after we merged #306. Please feel free to open a new ticket if a different issue was revealed by that fix.

Thanks,
Alex

**Closed by alubbock** 2018-01-13 02:52 UTC

**Comment by glucksfall** [comment] 2018-02-13 18:55
Hello Alex,

Thank you for taking into account this issue. I didn't try the Github version of PySB and keep using the pypi version. So, I don't know if the Github version solves this issue. Sorry about that.

However, I'm here to report a weird behaviour I don't know is related or not to this ticket. I have two model and I simulate them using `kappa.run_simulation(model, time = 60, points = 60)` after `bng.run_ssa(model, t_end = 60, n_steps = 60)`. For one the models, these two commands work perfectly. Rather, for the another model `kappa.run_simulation(model, time = 10000, points = 1000)` raise `TypeError: can't concat str to bytes` only if it was ran after `bng.run_ssa(model, t_end = 10000, n_steps = 1000)`. Inverting the commands, that is kappa.run_simulation(...) before bng.run_ssa(...), works smoothly. Also running only the kappa.run_simulation(...)

I can share the jupyter notebooks if you need to see the whole code. They are just models I use to practice analysis to further show them in my presentations.

Best regards

**Comment by alubbock** [comment] 2018-02-13 20:33
Rodrigo, I'm unable to reproduce this. Please could you share a model where this happens and let me know what version of PySB you're using. Thanks.

**Comment by glucksfall** [comment] 2018-02-13 23:59
Hi Alex,
I have installed 1.5.0 for python3. You can download the jupyter notebooks at https://github.com/glucksfall/notebooks where the issue is present
Thanks
